// src/components/dashboard/Story-quest/storyContent.js
// ✅ PROGRESSIVE STORYTELLING: A1 → C2
// ✅ A1/A2: vocabulary-meaning based
// ✅ B1/B2: 20 scenes each (scenario-based)
// ✅ C1/C2: 25 scenes each (scenario-based)
// ✅ UPDATED: B1 garden uses /image/garden1.png
// ✅ UPDATED: B2 inevitable uses /image/inevitable2.png
// ✅ UPDATED: C1 legacy uses /image/legacy1.png
// ✅ UPDATED: C1 harmonious uses /image/harmonious2.png

export const STORY_ARCS = {
  // ══════════════════════════════════════════════════════════
  // 🟢 A1 — SIMPLE NARRATION (10 scenes)
  // ══════════════════════════════════════════════════════════
  'A1': {
    title: "Tom's First Day at School",
    scenes: [
      { text: "Tom walked into the big school for the first time.", vocabulary: "school", definition: "A place where children learn" },
      { text: "His new teacher greeted him with a warm smile.", vocabulary: "teacher", definition: "A person who teaches students" },
      { text: "He held a yellow pencil in his small hand.", vocabulary: "pencil", definition: "A tool used for writing" },
      { text: "Tom opened his book and looked at the pages.", vocabulary: "book", definition: "Pages with words bound together" },
      { text: "He sat on a wooden chair beside his classmate.", vocabulary: "chair", definition: "A seat with a back for one person" },
      { text: "At noon, he shared his lunch with a new friend.", vocabulary: "lunch", definition: "A meal eaten at midday" },
      { text: "Tom felt happy and smiled at everyone.", vocabulary: "happy", definition: "Feeling joy and pleasure" },
      { text: "He made a kind new friend on his first day.", vocabulary: "friend", definition: "A person you like and trust" },
      { text: "He was excited to learn new things every day.", vocabulary: "learn", definition: "To gain new knowledge" },
      { text: "After school, Tom walked back to his home.", vocabulary: "home", definition: "The place where you live" },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // 🟢 A2 — DESCRIPTIVE NARRATION (10 scenes)
  // ══════════════════════════════════════════════════════════
  'A2': {
    title: "The Lost Kitten",
    scenes: [
      { text: "One rainy evening, a tiny kitten was crying alone on the wet street.", vocabulary: "kitten", definition: "A baby cat" },
      { text: "She was hiding under a thick bush in the cold garden.", vocabulary: "garden", definition: "An area with plants and flowers" },
      { text: "Anna heard the sad sound and began to search the dark corners.", vocabulary: "search", definition: "To look for something" },
      { text: "After minutes of looking, she finally found the kitten shaking with fear.", vocabulary: "found", definition: "Discovered something" },
      { text: "The little kitten looked very hungry and its eyes were full of fear.", vocabulary: "hungry", definition: "Wanting or needing food" },
      { text: "Anna brought her home and poured warm milk into a small bowl.", vocabulary: "milk", definition: "A white drink from cows" },
      { text: "The kitten drank it all and began to feel warm and safe.", vocabulary: "warm", definition: "Slightly hot; not cold" },
      { text: "Soon her tiny eyes closed, and she began to sleep peacefully.", vocabulary: "sleep", definition: "To rest with your eyes closed" },
      { text: "Anna gently held the kitten close to cuddle her like a baby.", vocabulary: "cuddle", definition: "To hold someone closely with love" },
      { text: "From that quiet night on, the kitten became part of their loving family.", vocabulary: "family", definition: "Parents and their children" },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // 🟡 B1 — ATMOSPHERIC NARRATION (20 scenes)
  // ══════════════════════════════════════════════════════════
  'B1': {
    title: "The Secret Garden",
    scenes: [
      {
        text: "Behind the old abandoned house stood a garden that no one had entered for years.",
        vocabulary: "garden",
        image: "/image/garden1.png",
        definition: "A secluded area of land, often cultivated with plants and flowers, where one might seek peace or hide secrets.",
        question: "What does the garden being abandoned for years suggest about it?",
        choices: [
          { text: "It is filled with hidden secrets and mysteries waiting to be uncovered.", correct: true },
          { text: "It is a popular place where many people gather every day.", correct: false },
          { text: "It has been destroyed and nothing grows there anymore.", correct: false },
          { text: "It belongs to the government and is strictly off-limits.", correct: false },
        ],
      },
      {
        text: "Lily had always hoped to discover the secrets hidden within its ancient walls.",
        vocabulary: "discover",
        definition: "To uncover or bring to light something that was previously hidden, unknown, or unexplored.",
        question: "What do we learn about Lily from her desire to 'discover'?",
        choices: [
          { text: "She is naturally curious and longs to know the unknown.", correct: true },
          { text: "She wants to tear down the ancient walls of the garden.", correct: false },
          { text: "She is afraid of what might be hiding in the garden.", correct: false },
          { text: "She plans to sell the garden to make money.", correct: false },
        ],
      },
      {
        text: "One misty morning, she found a mysterious gate completely covered with twisted vines.",
        vocabulary: "mysterious",
        definition: "Something that evokes a sense of wonder or curiosity because it is difficult to understand or explain rationally.",
        question: "Why is the gate described as 'mysterious'?",
        choices: [
          { text: "Because it is hidden and difficult to explain, sparking curiosity.", correct: true },
          { text: "Because it is brightly painted and easy to notice.", correct: false },
          { text: "Because it is guarded by dangerous animals.", correct: false },
          { text: "Because it was recently built by the villagers.", correct: false },
        ],
      },
      {
        text: "As she pushed it open with a creak, the wild roses began to bloom everywhere.",
        vocabulary: "bloom",
        definition: "To produce flowers as part of a natural cycle of growth and renewal.",
        question: "What does the sudden blooming of roses suggest about the garden?",
        choices: [
          { text: "The garden is coming back to life after being neglected for years.", correct: true },
          { text: "The roses were planted just a few minutes ago.", correct: false },
          { text: "The garden has always been full of flowers every season.", correct: false },
          { text: "Someone is deliberately making the roses bloom artificially.", correct: false },
        ],
      },
      {
        text: "Every blossom filled the warm air with a sweet and delicate perfume.",
        vocabulary: "blossom",
        definition: "A flower or a mass of flowers on a tree or bush, often symbolizing new beginnings.",
        question: "What does the 'sweet and delicate perfume' imply about the garden's atmosphere?",
        choices: [
          { text: "The garden feels inviting, peaceful, and full of new life.", correct: true },
          { text: "The garden smells dangerous and unpleasant.", correct: false },
          { text: "The garden has a strong chemical smell from the flowers.", correct: false },
          { text: "The garden is completely empty with no flowers at all.", correct: false },
        ],
      },
      {
        text: "Soft petals fell gently onto the forgotten and mossy stone path.",
        vocabulary: "petals",
        definition: "The delicate, colorful parts of a flower that surround the reproductive center.",
        question: "What does the image of petals falling onto a 'forgotten' path suggest?",
        choices: [
          { text: "The garden has been neglected for a long time but is now being rediscovered.", correct: true },
          { text: "The path was recently cleaned and renovated by workers.", correct: false },
          { text: "The petals are made of plastic and cannot fall naturally.", correct: false },
          { text: "Someone is picking up all the petals before they fall.", correct: false },
        ],
      },
      {
        text: "A lovely fragrance drifted softly through the quiet and peaceful air.",
        vocabulary: "fragrance",
        definition: "A pleasant, sweet, and often lingering smell that evokes a sense of comfort or nostalgia.",
        question: "What is the effect of the fragrance on the atmosphere of the scene?",
        choices: [
          { text: "It makes the scene feel comforting and nostalgic.", correct: true },
          { text: "It makes the air smell like smoke and danger.", correct: false },
          { text: "It causes Lily to feel sick and dizzy.", correct: false },
          { text: "It signals that a storm is coming soon.", correct: false },
        ],
      },
      {
        text: "The gentle wind seemed to whisper ancient secrets in her waiting ear.",
        vocabulary: "whisper",
        definition: "To speak very softly and quietly, often to convey a secret or intimate thought.",
        question: "What does the personification of the wind 'whispering secrets' reveal?",
        choices: [
          { text: "It creates a magical, intimate mood that makes the garden feel alive.", correct: true },
          { text: "It shows that the wind is physically speaking in human language.", correct: false },
          { text: "It suggests that Lily is losing her mind in the garden.", correct: false },
          { text: "It proves that there are hidden people living in the walls.", correct: false },
        ],
      },
      {
        text: "It was the most peaceful and silent place she had ever seen.",
        vocabulary: "peaceful",
        definition: "A state of tranquility and calm, free from disturbance, noise, or conflict.",
        question: "What does Lily's reaction to the garden's peacefulness tell us?",
        choices: [
          { text: "She finds deep comfort and serenity in this hidden sanctuary.", correct: true },
          { text: "She is bored and wants to leave the garden immediately.", correct: false },
          { text: "She is scared of the silence and starts to scream.", correct: false },
          { text: "She plans to invite all her friends to party there.", correct: false },
        ],
      },
      {
        text: "Lily stood completely still, struck by the pure and timeless beauty before her.",
        vocabulary: "beauty",
        definition: "A combination of qualities that pleases the aesthetic senses, especially the sight.",
        question: "What does the phrase 'timeless beauty' suggest about the garden?",
        choices: [
          { text: "The garden's beauty feels eternal, untouched by time or change.", correct: true },
          { text: "The garden is brand new and was built yesterday.", correct: false },
          { text: "The garden is ugly and Lily wants to run away.", correct: false },
          { text: "The garden's beauty fades every hour of the day.", correct: false },
        ],
      },
      {
        text: "Beneath an old oak tree, she noticed a small fountain that had long stopped flowing.",
        vocabulary: "fountain",
        definition: "A structure that sends a stream of water into the air, often used as a decorative feature in gardens.",
        question: "What does the silent fountain symbolize about the garden's history?",
        choices: [
          { text: "The garden was once vibrant and full of life but has since become silent.", correct: true },
          { text: "The fountain is still working perfectly and water flows every day.", correct: false },
          { text: "The fountain was never meant to have water in the first place.", correct: false },
          { text: "Someone recently built the fountain as a modern addition.", correct: false },
        ],
      },
      {
        text: "Curious, she traced her fingers along the moss-covered stones of the fountain's edge.",
        vocabulary: "curious",
        definition: "Eager to know or learn something; showing a strong desire to explore or investigate.",
        question: "What does Lily's action of tracing her fingers reveal about her character?",
        choices: [
          { text: "She is a hands-on explorer who connects deeply with her surroundings.", correct: true },
          { text: "She is afraid to touch anything in the garden.", correct: false },
          { text: "She is only interested in destroying the old fountain.", correct: false },
          { text: "She is trying to clean the fountain for money.", correct: false },
        ],
      },
      {
        text: "Suddenly, she heard a faint melody drifting from somewhere deeper in the garden.",
        vocabulary: "melody",
        definition: "A sequence of musical notes that is satisfying or pleasant to listen to.",
        question: "What effect does hearing the 'faint melody' have on the scene?",
        choices: [
          { text: "It adds mystery and pulls Lily further into the garden's secrets.", correct: true },
          { text: "It makes Lily angry and she decides to leave immediately.", correct: false },
          { text: "It proves that the garden is a dangerous place to be.", correct: false },
          { text: "It shows that there are no secrets to be found at all.", correct: false },
        ],
      },
      {
        text: "Following the sound, she discovered a small boy sitting quietly on a stone bench.",
        vocabulary: "bench",
        definition: "A long seat for two or more people, typically made of wood or stone, often found outdoors.",
        question: "What does the presence of the small boy suggest about the garden?",
        choices: [
          { text: "The garden is not entirely abandoned; someone else shares its secret.", correct: true },
          { text: "The garden is now a public park open to everyone.", correct: false },
          { text: "The garden belongs to a large crowd of people.", correct: false },
          { text: "The boy is a statue that Lily is imagining.", correct: false },
        ],
      },
      {
        text: "He hummed softly, unaware that anyone had entered his hidden sanctuary.",
        vocabulary: "sanctuary",
        definition: "A place of refuge or safety; a sacred or peaceful place where one can feel protected.",
        question: "Why is the garden referred to as a 'sanctuary'?",
        choices: [
          { text: "It is a safe and peaceful place that offers refuge from the outside world.", correct: true },
          { text: "It is a busy public area filled with loud noises.", correct: false },
          { text: "It is a dangerous place where no one wants to go.", correct: false },
          { text: "It is an ordinary garden with nothing special about it.", correct: false },
        ],
      },
      {
        text: "Lily hesitated, unsure whether to disturb his peaceful moment of solitude.",
        vocabulary: "solitude",
        definition: "The state or situation of being alone, often in a peaceful or reflective way.",
        question: "What does Lily's hesitation reveal about her personality?",
        choices: [
          { text: "She is considerate and respects the peaceful solitude of others.", correct: true },
          { text: "She is rude and immediately interrupts the boy.", correct: false },
          { text: "She is too shy to ever speak to anyone.", correct: false },
          { text: "She wants to scare him and ruin his day.", correct: false },
        ],
      },
      {
        text: "But the boy turned, smiled gently, and welcomed her without a single word.",
        vocabulary: "welcome",
        definition: "To greet someone in a warm and friendly way, making them feel accepted and comfortable.",
        question: "What does the boy's silent welcome tell us about him?",
        choices: [
          { text: "He is kind and accepting, sharing the garden's peace with her.", correct: true },
          { text: "He is angry that someone has discovered his secret place.", correct: false },
          { text: "He is frightened and runs away without looking back.", correct: false },
          { text: "He is unfriendly and wants her to leave immediately.", correct: false },
        ],
      },
      {
        text: "Together, they sat in the warm sunlight and listened to the garden's quiet rhythms.",
        vocabulary: "rhythm",
        definition: "A strong, regular, repeated pattern of movement or sound, often creating a sense of harmony.",
        question: "What does the phrase 'the garden's quiet rhythms' suggest about nature?",
        choices: [
          { text: "Nature has its own gentle patterns that bring peace to those who notice.", correct: true },
          { text: "Nature is chaotic and unpredictable without any order.", correct: false },
          { text: "Nature only makes loud and frightening noises.", correct: false },
          { text: "Nature is completely silent at all times.", correct: false },
        ],
      },
      {
        text: "For the first time in years, the garden no longer felt empty or forgotten.",
        vocabulary: "forgotten",
        definition: "No longer remembered or considered; left behind or neglected over time.",
        question: "What has changed about the garden by the end of the story?",
        choices: [
          { text: "It has been rediscovered and given new life through the presence of friendship.", correct: true },
          { text: "It has been demolished and replaced with a modern building.", correct: false },
          { text: "It has become even more empty and abandoned than before.", correct: false },
          { text: "It has been sold to a company for commercial use.", correct: false },
        ],
      },
      {
        text: "Lily knew she had found something far more precious than any hidden treasure.",
        vocabulary: "precious",
        definition: "Of great value because of being rare, expensive, or important; something deeply cherished.",
        question: "What is the 'precious' thing Lily found in the garden?",
        choices: [
          { text: "A meaningful friendship and a peaceful place of belonging.", correct: true },
          { text: "A chest full of gold and jewels hidden in the ground.", correct: false },
          { text: "A magical spell that grants her any wish.", correct: false },
          { text: "A piece of land she can sell for a large amount of money.", correct: false },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // 🟡 B2 — COMPLEX NARRATION (20 scenes)
  // ══════════════════════════════════════════════════════════
  'B2': {
    title: "The Time Traveler's Diary",
    scenes: [
      {
        text: "The worn diary had been written over a century ago by hands she would never meet.",
        vocabulary: "century",
        definition: "A period of one hundred years, often used to mark significant historical eras or generational gaps.",
        question: "What does 'hands she would never meet' convey about the diary's author?",
        choices: [
          { text: "The author lived long ago, in a different generation from Maya.", correct: true },
          { text: "The author is a close friend Maya talks to every day.", correct: false },
          { text: "The author is Maya's neighbor who lives next door.", correct: false },
          { text: "The author is someone Maya will meet next week.", correct: false },
        ],
      },
      {
        text: "It once belonged to a distant ancestor whose name had faded from memory.",
        vocabulary: "ancestor",
        definition: "A person from whom one is descended, typically more distant than a grandparent, often carrying historical significance.",
        question: "What is the emotional impact of the ancestor's name 'fading from memory'?",
        choices: [
          { text: "It creates a sense of loss and mystery about the family's past.", correct: true },
          { text: "It makes the diary feel unimportant and worthless.", correct: false },
          { text: "It proves that the ancestor never really existed.", correct: false },
          { text: "It suggests the family deliberately erased all records.", correct: false },
        ],
      },
      {
        text: "Each generation in her family had carefully kept it hidden and safe.",
        vocabulary: "generation",
        definition: "All of the people born and living at about the same time, regarded collectively.",
        question: "What does the family's care in keeping the diary safe reveal?",
        choices: [
          { text: "The diary holds significant value and secrets for the family.", correct: true },
          { text: "The family is ashamed of the diary and wants to hide it.", correct: false },
          { text: "The family forgot the diary existed in a storage box.", correct: false },
          { text: "The diary was accidentally left behind by strangers.", correct: false },
        ],
      },
      {
        text: "Maya was determined to preserve the fragile pages before time destroyed them forever.",
        vocabulary: "preserve",
        definition: "To maintain something in its original state or protect it from decay, damage, or destruction over time.",
        question: "What does Maya's determination to 'preserve' the diary tell us about her?",
        choices: [
          { text: "She values history and feels responsible for protecting her heritage.", correct: true },
          { text: "She wants to rewrite the diary with her own handwriting.", correct: false },
          { text: "She plans to burn the diary to hide its secrets.", correct: false },
          { text: "She thinks the diary is worthless and should be discarded.", correct: false },
        ],
      },
      {
        text: "Inside were writings in a strange, ancient language no one spoke anymore.",
        vocabulary: "ancient",
        definition: "Belonging to the very distant past and no longer in existence, often implying great historical value.",
        question: "What challenge does the 'ancient language' present to Maya?",
        choices: [
          { text: "She must decipher a forgotten language to understand the diary.", correct: true },
          { text: "The language is easy and she reads it fluently right away.", correct: false },
          { text: "The language is the same as the one she speaks daily.", correct: false },
          { text: "The language is written in modern English only.", correct: false },
        ],
      },
      {
        text: "The old manuscript was difficult to read, and its ink had almost vanished.",
        vocabulary: "manuscript",
        definition: "A handwritten document, especially one that is historically or culturally significant.",
        question: "What does the fading ink symbolize about the diary's history?",
        choices: [
          { text: "The passage of time is slowly erasing the past, making it fragile.", correct: true },
          { text: "The ink was intentionally erased by someone recently.", correct: false },
          { text: "The manuscript was printed by a modern machine.", correct: false },
          { text: "The ink fading means the diary has no importance.", correct: false },
        ],
      },
      {
        text: "She spent weeks desperately trying to decipher every faint and broken sentence.",
        vocabulary: "decipher",
        definition: "To succeed in understanding or interpreting something that is difficult to read or comprehend.",
        question: "What does 'desperately trying to decipher' reveal about Maya's mindset?",
        choices: [
          { text: "She is obsessed and deeply committed to uncovering the truth.", correct: true },
          { text: "She is lazy and gives up after a few minutes.", correct: false },
          { text: "She is uninterested and only reads for fun.", correct: false },
          { text: "She is angry and wants to destroy the manuscript.", correct: false },
        ],
      },
      {
        text: "Along the way, she would encounter many surprises that shook her beliefs.",
        vocabulary: "encounter",
        definition: "To unexpectedly experience or be faced with something, especially a difficulty or a surprising event.",
        question: "What does 'surprises that shook her beliefs' foreshadow?",
        choices: [
          { text: "Maya will discover shocking truths that change her worldview.", correct: true },
          { text: "Maya will find everything she already expected to find.", correct: false },
          { text: "Maya will become bored and abandon her research.", correct: false },
          { text: "Maya will meet her friends for a birthday party.", correct: false },
        ],
      },
      {
        text: "Some entries described peculiar dreams and unsettling visions of the future.",
        vocabulary: "peculiar",
        definition: "Strange or odd in a way that is slightly unsettling or difficult to explain.",
        question: "What is the effect of the diary containing 'unsettling visions of the future'?",
        choices: [
          { text: "It suggests the diary may have supernatural or prophetic powers.", correct: true },
          { text: "It proves the diary is a simple cookbook with recipes.", correct: false },
          { text: "It shows the diary was written by a young child.", correct: false },
          { text: "It means the diary is completely boring and ordinary.", correct: false },
        ],
      },
      {
        text: "In the end, her discovery of the truth was completely inevitable.",
        vocabulary: "inevitable",
        image: "/image/inevitable2.png",
        definition: "Certain to happen; unavoidable, often used to describe an event that was destined to occur.",
        question: "Why does the narrator describe Maya's discovery as 'inevitable'?",
        choices: [
          { text: "Because she was so determined that finding the truth was only a matter of time.", correct: true },
          { text: "Because she never actually looked for the truth at all.", correct: false },
          { text: "Because the truth was written on the front cover of the diary.", correct: false },
          { text: "Because someone told her the truth from the very beginning.", correct: false },
        ],
      },
      {
        text: "After months of deciphering, Maya experienced a profound revelation — the name written in the diary was her own.",
        vocabulary: "revelation",
        definition: "A surprising and previously unknown fact that is made known to others.",
        question: "Why is finding her own name in the diary considered a 'revelation'?",
        choices: [
          { text: "It reveals a shocking and unexpected connection between Maya and the diary.", correct: true },
          { text: "It shows that the diary is a simple grocery list.", correct: false },
          { text: "It proves the diary was written by a complete stranger.", correct: false },
          { text: "It means the diary has no real significance at all.", correct: false },
        ],
      },
      {
        text: "Tucked between two pages was an old photograph whose face bore a striking resemblance to hers.",
        vocabulary: "resemblance",
        definition: "The state of resembling or being alike in appearance or character.",
        question: "What does the 'striking resemblance' between Maya and the photograph suggest?",
        choices: [
          { text: "She is somehow deeply connected to the person in the photograph.", correct: true },
          { text: "The photograph was randomly placed in the diary.", correct: false },
          { text: "The person in the photograph is a famous celebrity.", correct: false },
          { text: "The resemblance is just a coincidence with no meaning.", correct: false },
        ],
      },
      {
        text: "She wondered if the diary could possibly be authentic, or if it was merely an elaborate forgery.",
        vocabulary: "authentic",
        definition: "Of undisputed origin and not a copy; genuine and real.",
        question: "Why is it important for Maya to determine if the diary is 'authentic'?",
        choices: [
          { text: "The truth of the diary's origin determines whether its secrets are real.", correct: true },
          { text: "She wants to sell it for a high price at an auction.", correct: false },
          { text: "She plans to destroy it if it turns out to be fake.", correct: false },
          { text: "She doesn't care about its authenticity at all.", correct: false },
        ],
      },
      {
        text: "Her grandmother finally confessed that the diary was a secret inheritance kept hidden for generations.",
        vocabulary: "inheritance",
        definition: "Something that is received from a predecessor or from the past, often with lasting significance.",
        question: "What does the diary being a 'secret inheritance' reveal about the family?",
        choices: [
          { text: "The family has been hiding an important legacy for generations.", correct: true },
          { text: "The family forgot about the diary completely.", correct: false },
          { text: "The diary was given to them by a stranger recently.", correct: false },
          { text: "The inheritance is just money and property.", correct: false },
        ],
      },
      {
        text: "The final pages contained cryptic messages that seemed to predict events decades before they happened.",
        vocabulary: "cryptic",
        definition: "Having a meaning that is mysterious or obscure, difficult to interpret.",
        question: "Why are the messages described as 'cryptic'?",
        choices: [
          { text: "They are mysterious and difficult to understand at first glance.", correct: true },
          { text: "They are clear and easy to read immediately.", correct: false },
          { text: "They are written in modern English only.", correct: false },
          { text: "They contain no meaning whatsoever.", correct: false },
        ],
      },
      {
        text: "A sudden premonition washed over her — she knew something important was about to happen.",
        vocabulary: "premonition",
        definition: "A strong feeling that something is about to happen, especially something significant or unsettling.",
        question: "What does Maya's 'premonition' suggest about her state of mind?",
        choices: [
          { text: "She senses that the diary's secrets are leading to something significant.", correct: true },
          { text: "She is simply hungry and tired from reading.", correct: false },
          { text: "She is imagining things with no basis in reality.", correct: false },
          { text: "She has completely forgotten about the diary.", correct: false },
        ],
      },
      {
        text: "Now she faced a difficult dilemma: should she share the diary's secrets with her family or keep them hidden?",
        vocabulary: "dilemma",
        definition: "A situation in which a difficult choice has to be made between two or more alternatives.",
        question: "Why is Maya's situation considered a 'dilemma'?",
        choices: [
          { text: "She must choose between two difficult options with serious consequences.", correct: true },
          { text: "She has no choice to make at all.", correct: false },
          { text: "She is happy and carefree with no problems.", correct: false },
          { text: "She has already decided what to do easily.", correct: false },
        ],
      },
      {
        text: "A sudden insight struck her — the diary was not just a record of the past, but a guide for the future.",
        vocabulary: "insight",
        definition: "A deep and accurate understanding of something, often sudden and intuitive.",
        question: "What does Maya's 'insight' reveal about the diary's purpose?",
        choices: [
          { text: "The diary serves as both a historical record and a guide for what is to come.", correct: true },
          { text: "The diary is only useful as a decoration on a shelf.", correct: false },
          { text: "The diary has no real purpose or meaning.", correct: false },
          { text: "The diary was meant to be thrown away long ago.", correct: false },
        ],
      },
      {
        text: "Hidden within the spine of the diary was a concealed letter that had never been opened.",
        vocabulary: "concealed",
        definition: "Kept secret or hidden from view; not allowed to be seen or known.",
        question: "Why is the letter described as 'concealed'?",
        choices: [
          { text: "It was deliberately hidden inside the spine of the diary.", correct: true },
          { text: "It was placed on top of the diary in plain sight.", correct: false },
          { text: "It was never actually inside the diary at all.", correct: false },
          { text: "It was written by Maya herself recently.", correct: false },
        ],
      },
      {
        text: "The letter revealed a legacy that would change her family's future forever.",
        vocabulary: "legacy",
        definition: "Something handed down by a predecessor, often with lasting significance or value.",
        question: "What does the 'legacy' in the letter represent for Maya's family?",
        choices: [
          { text: "A lasting gift or responsibility passed down through generations.", correct: true },
          { text: "A worthless piece of paper with no meaning.", correct: false },
          { text: "A random document with no family connection.", correct: false },
          { text: "A letter that should be immediately destroyed.", correct: false },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // 🟠 C1 — LITERARY NARRATION (25 scenes)
  // ══════════════════════════════════════════════════════════
  'C1': {
    title: "The Pianist's Farewell",
    scenes: [
      {
        text: "The grand symphony began with a single gentle note that hung in the air like mist.",
        vocabulary: "symphony",
        definition: "An elaborate musical composition for a full orchestra, typically in four movements.",
        question: "What does the comparison of the note to 'mist' suggest about the music's quality?",
        choices: [
          { text: "The music is delicate, ethereal, and lingers in the atmosphere.", correct: true },
          { text: "The music is loud, aggressive, and jarring.", correct: false },
          { text: "The music is completely silent and inaudible.", correct: false },
          { text: "The music is fast, chaotic, and mechanical.", correct: false },
        ],
      },
      {
        text: "Slowly, the music rose in a powerful crescendo that seemed to shake the very walls.",
        vocabulary: "crescendo",
        definition: "A gradual increase in the loudness or intensity of a sound or piece of music.",
        question: "What effect does the 'powerful crescendo' have on the listeners?",
        choices: [
          { text: "It overwhelms them with the intensity and power of the music.", correct: true },
          { text: "It puts them to sleep with its gentle whisper.", correct: false },
          { text: "It makes them laugh at the silliness of the sound.", correct: false },
          { text: "It causes them to leave the hall in disappointment.", correct: false },
        ],
      },
      {
        text: "Every note was poignant and full of a quiet sorrow only old men understand.",
        vocabulary: "poignant",
        definition: "Evoking a keen sense of sadness or regret, often through a deeply touching or emotionally intense experience.",
        question: "What does 'a quiet sorrow only old men understand' imply?",
        choices: [
          { text: "The music speaks to a deep, life-earned wisdom about loss and time.", correct: true },
          { text: "The music is only meant for young children to enjoy.", correct: false },
          { text: "The music is cheerful and makes everyone dance.", correct: false },
          { text: "The music has no emotional weight at all.", correct: false },
        ],
      },
      {
        text: "He was a virtuoso who had mastered his craft for decades of silent devotion.",
        vocabulary: "virtuoso",
        definition: "A person highly skilled in music or another artistic pursuit, demonstrating exceptional technical ability.",
        question: "What does the phrase 'silent devotion' reveal about the pianist's life?",
        choices: [
          { text: "He committed years of unseen practice and dedication to his art.", correct: true },
          { text: "He never practiced and was naturally gifted without effort.", correct: false },
          { text: "He was lazy and only played music for fun.", correct: false },
          { text: "He secretly hated music and wanted to quit.", correct: false },
        ],
      },
      {
        text: "The deep resonance of the piano filled the entire hall like a rising tide.",
        vocabulary: "resonance",
        definition: "The quality in a sound of being deep, full, and reverberating, often evoking an emotional response.",
        question: "What does the 'rising tide' metaphor suggest about the piano's sound?",
        choices: [
          { text: "The sound swells and fills the entire space in an unstoppable way.", correct: true },
          { text: "The sound is quiet and cannot be heard by anyone.", correct: false },
          { text: "The sound is harsh and causes the audience to cover their ears.", correct: false },
          { text: "The sound is exactly the same as a storm's thunder.", correct: false },
        ],
      },
      {
        text: "A gentle melancholy settled over the silent audience as they listened, breathless.",
        vocabulary: "melancholy",
        definition: "A profound and pervasive feeling of sadness or gloom, often accompanied by a thoughtful or contemplative mood.",
        question: "Why is the audience described as 'breathless' and full of 'melancholy'?",
        choices: [
          { text: "The music moved them deeply, evoking sadness and awe simultaneously.", correct: true },
          { text: "They were tired from walking and wanted to go home.", correct: false },
          { text: "They were angry that the performance was so loud.", correct: false },
          { text: "They were laughing hysterically at the pianist's mistakes.", correct: false },
        ],
      },
      {
        text: "Every chord was perfectly harmonious, weaving threads of joy and grief together.",
        vocabulary: "harmonious",
        image: "/image/harmonious2.png",
        definition: "Forming a pleasing or consistent whole; free from disagreement or dissonance.",
        question: "What does 'weaving threads of joy and grief together' mean?",
        choices: [
          { text: "The music blended contrasting emotions into one unified experience.", correct: true },
          { text: "The music only expressed sadness and nothing else.", correct: false },
          { text: "The music only expressed happiness without any sorrow.", correct: false },
          { text: "The music was disjointed and hard to follow.", correct: false },
        ],
      },
      {
        text: "The melody was deeply evocative of forgotten memories and lost loves.",
        vocabulary: "evocative",
        definition: "Bringing strong images, memories, or feelings to mind, often through sensory details.",
        question: "What effect does the 'evocative' melody have on the audience?",
        choices: [
          { text: "It stirs up personal memories and hidden emotions within them.", correct: true },
          { text: "It makes them forget everything that ever happened in their lives.", correct: false },
          { text: "It causes them to feel absolutely nothing at all.", correct: false },
          { text: "It reminds them only of their homework and chores.", correct: false },
        ],
      },
      {
        text: "The final movement was calm, slow, and utterly serene, like a peaceful farewell.",
        vocabulary: "serene",
        definition: "Calm, peaceful, and untroubled; free from agitation or disturbance.",
        question: "Why does the narrator compare the ending to 'a peaceful farewell'?",
        choices: [
          { text: "The music concludes with a sense of quiet closure and acceptance.", correct: true },
          { text: "The pianist suddenly stops playing and walks off angrily.", correct: false },
          { text: "The audience leaves the hall without listening to the end.", correct: false },
          { text: "The music ends abruptly with a loud clash of cymbals.", correct: false },
        ],
      },
      {
        text: "When it ended, the performance felt truly transcendent — beyond music itself.",
        vocabulary: "transcendent",
        definition: "Beyond or above the range of normal or merely physical human experience; surpassing the ordinary.",
        question: "What does 'transcendent' suggest about the final experience of the performance?",
        choices: [
          { text: "The experience went beyond ordinary music and touched something spiritual.", correct: true },
          { text: "The performance was average and forgettable.", correct: false },
          { text: "The performance was so bad that no one enjoyed it.", correct: false },
          { text: "The performance was exactly what everyone expected.", correct: false },
        ],
      },
      {
        text: "The pianist rose slowly, his frail hands trembling from years of relentless practice.",
        vocabulary: "frail",
        definition: "Weak and delicate, especially from age or illness; easily broken or damaged.",
        question: "What does the description of his 'frail hands' convey about the pianist?",
        choices: [
          { text: "He is aging and physically weakened, yet still devoted to his art.", correct: true },
          { text: "He is young, strong, and in perfect health.", correct: false },
          { text: "He has never actually played the piano before.", correct: false },
          { text: "He is pretending to be old for dramatic effect.", correct: false },
        ],
      },
      {
        text: "The audience erupted in thunderous applause, a testament to his enduring legacy.",
        vocabulary: "legacy",
        image: "/image/legacy1.png",
        definition: "Something handed down by a predecessor, often with lasting significance or value.",
        question: "What does the 'enduring legacy' refer to in this context?",
        choices: [
          { text: "The lasting impact of his music and dedication on future generations.", correct: true },
          { text: "A large sum of money he inherited from his parents.", correct: false },
          { text: "A physical building that he owned in the city.", correct: false },
          { text: "A promise he made to his childhood friend.", correct: false },
        ],
      },
      {
        text: "Yet behind the applause, there lingered an unspoken sorrow — this would be his final performance.",
        vocabulary: "unspoken",
        definition: "Not expressed in words; understood without being said aloud.",
        question: "What makes the sorrow 'unspoken'?",
        choices: [
          { text: "Everyone feels it deeply but no one wants to say it aloud.", correct: true },
          { text: "No one in the audience feels any emotion at all.", correct: false },
          { text: "The sorrow is loudly announced by the pianist.", correct: false },
          { text: "The pianist is unaware he is retiring.", correct: false },
        ],
      },
      {
        text: "He had grown weary of the relentless demands of touring and the hollow praise of critics.",
        vocabulary: "weary",
        definition: "Feeling or showing extreme tiredness, especially from prolonged effort or stress.",
        question: "Why had the pianist grown 'weary' of his career?",
        choices: [
          { text: "The constant touring and superficial praise had drained him over time.", correct: true },
          { text: "He had just started his career and was excited.", correct: false },
          { text: "He had never performed in front of an audience before.", correct: false },
          { text: "He was angry at the audience for not clapping.", correct: false },
        ],
      },
      {
        text: "A young girl in the front row watched him with an expression of pure awe.",
        vocabulary: "awe",
        definition: "A feeling of reverential respect mixed with fear or wonder.",
        question: "What does the girl's expression of 'awe' reveal about the pianist?",
        choices: [
          { text: "He is a figure of immense inspiration to the next generation.", correct: true },
          { text: "He is a frightening figure that scares children.", correct: false },
          { text: "He is an ordinary person with no special talent.", correct: false },
          { text: "He is a stranger whom no one recognizes.", correct: false },
        ],
      },
      {
        text: "He paused at the edge of the stage, his gaze lingering on the grand piano one last time.",
        vocabulary: "linger",
        definition: "To stay in a place longer than necessary, often because of reluctance to leave.",
        question: "Why does his gaze 'linger' on the piano?",
        choices: [
          { text: "He is reluctant to say goodbye to the instrument that defined his life.", correct: true },
          { text: "He has forgotten how to play and is confused.", correct: false },
          { text: "He is angry at the piano for malfunctioning.", correct: false },
          { text: "He is looking for a lost object underneath it.", correct: false },
        ],
      },
      {
        text: "A single tear traced down his cheek, silent testimony to a lifetime of devotion.",
        vocabulary: "testimony",
        definition: "A formal or solemn declaration or evidence of something; proof of a fact or feeling.",
        question: "What does the tear serve as 'testimony' to?",
        choices: [
          { text: "It proves the depth of his emotional commitment to music.", correct: true },
          { text: "It shows he is sad because he lost his wallet.", correct: false },
          { text: "It means he is allergic to the piano keys.", correct: false },
          { text: "It indicates he is angry at the audience.", correct: false },
        ],
      },
      {
        text: "Backstage, his old mentor waited in the shadows, nodding with quiet approval.",
        vocabulary: "mentor",
        definition: "An experienced and trusted adviser who guides a less experienced person.",
        question: "What is the role of the pianist's 'mentor' in this scene?",
        choices: [
          { text: "He is an older guide who shaped the pianist's journey and understands him.", correct: true },
          { text: "He is a random stranger who wandered backstage.", correct: false },
          { text: "He is a rival who wants to sabotage the pianist.", correct: false },
          { text: "He is a young child who knows nothing about music.", correct: false },
        ],
      },
      {
        text: "The old man spoke in a hushed tone, praising the pianist's courage to finally let go.",
        vocabulary: "hushed",
        definition: "Characterized by silence or quietness; subdued in tone.",
        question: "Why is the mentor's tone described as 'hushed'?",
        choices: [
          { text: "The moment is intimate and reverent, calling for quiet respect.", correct: true },
          { text: "He is shouting loudly so everyone can hear.", correct: false },
          { text: "He is afraid of being overheard by enemies.", correct: false },
          { text: "He has lost his voice and can only whisper.", correct: false },
        ],
      },
      {
        text: "The pianist replied with a fragile smile, acknowledging the bittersweet end of an era.",
        vocabulary: "bittersweet",
        definition: "Arousing pleasure accompanied by sadness; pleasant but tinged with regret.",
        question: "Why is the end of his career described as 'bittersweet'?",
        choices: [
          { text: "It brings both joy for his legacy and sadness for its ending.", correct: true },
          { text: "It is purely joyful with no trace of sadness.", correct: false },
          { text: "It is purely sad with no positive elements.", correct: false },
          { text: "It has no emotional significance at all.", correct: false },
        ],
      },
      {
        text: "Outside, the city lights glittered like a distant constellation, indifferent to his departure.",
        vocabulary: "indifferent",
        definition: "Having no particular interest or sympathy; unconcerned about something.",
        question: "What does the city's 'indifference' contrast with?",
        choices: [
          { text: "It contrasts with the deeply personal and emotional moment he is experiencing.", correct: true },
          { text: "It matches his excitement about moving to a new city.", correct: false },
          { text: "It shows that the city is angry at him for leaving.", correct: false },
          { text: "It proves the city is empty and abandoned.", correct: false },
        ],
      },
      {
        text: "He walked toward the exit with measured steps, each one a quiet goodbye to the stage.",
        vocabulary: "measured",
        definition: "Slow, careful, and deliberate; done with careful consideration.",
        question: "Why are his steps described as 'measured'?",
        choices: [
          { text: "He walks deliberately and thoughtfully, savoring each final step.", correct: true },
          { text: "He is running frantically to escape the building.", correct: false },
          { text: "He is stumbling and falling constantly.", correct: false },
          { text: "He is dancing joyfully out of the theater.", correct: false },
        ],
      },
      {
        text: "At the doorway, he turned back one final time, as if imprinting the moment on his soul.",
        vocabulary: "imprinting",
        definition: "Fixing something firmly in the mind or memory, so it remains vivid and permanent.",
        question: "What does 'imprinting the moment on his soul' suggest about the pianist?",
        choices: [
          { text: "He wants to preserve this final memory forever within himself.", correct: true },
          { text: "He is trying to forget everything as quickly as possible.", correct: false },
          { text: "He is physically writing something on a wall.", correct: false },
          { text: "He is not emotionally affected by the moment.", correct: false },
        ],
      },
      {
        text: "And so, the curtain fell on a life defined not by fame, but by an unwavering love for music.",
        vocabulary: "unwavering",
        definition: "Steady and not changing; firm and resolute in purpose or commitment.",
        question: "What does 'unwavering love for music' reveal about the pianist's life?",
        choices: [
          { text: "His commitment to music remained constant and true throughout his life.", correct: true },
          { text: "His love for music changed constantly and was unreliable.", correct: false },
          { text: "He never really loved music at all.", correct: false },
          { text: "His career was defined only by money and fame.", correct: false },
        ],
      },
      {
        text: "In the stillness that followed, there was a final cadence — a soft, rhythmic echo of everything he had given to the world.",
        vocabulary: "cadence",
        definition: "A rhythm or flow of sound, especially in music or speech; a sequence of notes that brings a phrase or piece to a close.",
        question: "What does the 'final cadence' symbolize in this scene?",
        choices: [
          { text: "It symbolizes the peaceful, musical closure of his lifelong career.", correct: true },
          { text: "It represents a loud, chaotic ending to the performance.", correct: false },
          { text: "It indicates that he forgot how to play the piano.", correct: false },
          { text: "It shows that the audience was angry and left.", correct: false },
        ],
      },
    ],
  },

  // ══════════════════════════════════════════════════════════
  // 🔴 C2 — PHILOSOPHICAL NARRATION (25 scenes)
  // ══════════════════════════════════════════════════════════
  'C2': {
    title: "The Architect of Dreams",
    scenes: [
      {
        text: "She envisioned a utopia where all people lived in peace, bound by no borders of fear.",
        vocabulary: "utopia",
        definition: "An imagined place or state of things in which everything is perfect, often used to describe an ideal society.",
        question: "What is the central characteristic of the 'utopia' she envisioned?",
        choices: [
          { text: "A perfect society where fear no longer divides people.", correct: true },
          { text: "A world ruled by strict laws and heavy borders.", correct: false },
          { text: "A society in which everyone must compete for survival.", correct: false },
          { text: "A world where only the strongest individuals thrive.", correct: false },
        ],
      },
      {
        text: "Her design challenged the existing paradigm of architecture and the limits of imagination.",
        vocabulary: "paradigm",
        definition: "A typical example or pattern of something; a distinct set of concepts or thought patterns.",
        question: "What does it mean that her design 'challenged the existing paradigm'?",
        choices: [
          { text: "She defied the traditional rules and conventions of architecture.", correct: true },
          { text: "She followed every traditional rule without any changes.", correct: false },
          { text: "She copied the designs of older architects exactly.", correct: false },
          { text: "She refused to design anything at all.", correct: false },
        ],
      },
      {
        text: "Yet she knew that all earthly things are ephemeral — mere shadows on a passing wall.",
        vocabulary: "ephemeral",
        definition: "Existing or enduring for only a very brief period, often emphasizing the fleeting nature of life or beauty.",
        question: "What philosophical idea does the phrase 'shadows on a passing wall' convey?",
        choices: [
          { text: "Everything in life is temporary, transient, and ultimately fleeting.", correct: true },
          { text: "Buildings last forever and never fade over time.", correct: false },
          { text: "Shadows are the most important things in life.", correct: false },
          { text: "Everything in the world is permanent and unchanging.", correct: false },
        ],
      },
      {
        text: "Her work created a striking juxtaposition of ancient memory and modern ambition.",
        vocabulary: "juxtaposition",
        definition: "The arrangement of two or more distinct concepts or items side-by-side to highlight their striking contrast or unexpected similarities.",
        question: "What does the 'juxtaposition' of ancient memory and modern ambition create?",
        choices: [
          { text: "A powerful contrast between the past and the future within her work.", correct: true },
          { text: "A complete lack of any difference between old and new.", correct: false },
          { text: "A design that only focuses on modern technology.", correct: false },
          { text: "A building that looks exactly like every other building.", correct: false },
        ],
      },
      {
        text: "Each structure she drew raised an existential question about why we build at all.",
        vocabulary: "existential",
        definition: "Relating to human existence or the experience of existing, often dealing with questions of meaning and purpose.",
        question: "What kind of 'existential question' does her architecture provoke?",
        choices: [
          { text: "A profound question about the meaning and purpose of human creation.", correct: true },
          { text: "A simple question about what color to paint the walls.", correct: false },
          { text: "A question about which materials are the cheapest.", correct: false },
          { text: "A question about where to park the cars.", correct: false },
        ],
      },
      {
        text: "She aimed for something truly sublime — beauty that outlives its maker.",
        vocabulary: "sublime",
        definition: "Of such excellence, grandeur, or beauty as to inspire great admiration or awe.",
        question: "What does 'beauty that outlives its maker' mean for the architect?",
        choices: [
          { text: "She wants to create something that will inspire awe long after she is gone.", correct: true },
          { text: "She wants to destroy her work before she dies.", correct: false },
          { text: "She wants her work to be forgotten after her death.", correct: false },
          { text: "She is only interested in short-lived, temporary creations.", correct: false },
        ],
      },
      {
        text: "There was a clear dichotomy between form and function, between art and purpose.",
        vocabulary: "dichotomy",
        definition: "A division or contrast between two things that are or are represented as being opposed or entirely different.",
        question: "What does the 'dichotomy between form and function' suggest about her struggle?",
        choices: [
          { text: "She constantly balanced the tension between beauty and practicality.", correct: true },
          { text: "She only cared about function and ignored all beauty.", correct: false },
          { text: "She only cared about beauty and ignored all function.", correct: false },
          { text: "She thought form and function were exactly the same thing.", correct: false },
        ],
      },
      {
        text: "She pondered metaphysical questions while she worked — questions no one could answer.",
        vocabulary: "metaphysical",
        definition: "Relating to the transcendent or to a reality beyond what is perceptible to the senses.",
        question: "What kind of 'metaphysical questions' might she have been pondering?",
        choices: [
          { text: "Deep questions about existence, reality, and the nature of being.", correct: true },
          { text: "Simple questions about what time lunch is served.", correct: false },
          { text: "Practical questions about where to buy materials.", correct: false },
          { text: "Questions about what her coworkers think of her.", correct: false },
        ],
      },
      {
        text: "Her aesthetic taste was refined, bold, unique, and unmistakably her own.",
        vocabulary: "aesthetic",
        definition: "Concerned with beauty or the appreciation of beauty, often reflecting a particular artistic philosophy.",
        question: "What does the description of her 'aesthetic taste' reveal about her as an artist?",
        choices: [
          { text: "She has a distinct and personal vision that sets her apart from others.", correct: true },
          { text: "She has no personal style and copies everyone else.", correct: false },
          { text: "She does not care about beauty at all in her work.", correct: false },
          { text: "She follows whatever trend is currently popular.", correct: false },
        ],
      },
      {
        text: "Her final creation was ethereal and almost dream-like — a glimpse of another world.",
        vocabulary: "ethereal",
        definition: "Extremely delicate and light in a way that seems too perfect for this world; heavenly or spiritual.",
        question: "What does the description of her final creation as 'ethereal' suggest?",
        choices: [
          { text: "Her work transcends reality and feels almost like something from a dream.", correct: true },
          { text: "Her work is heavy, solid, and entirely grounded in reality.", correct: false },
          { text: "Her work is ugly and unimpressive to those who see it.", correct: false },
          { text: "Her work is an exact copy of a famous historical monument.", correct: false },
        ],
      },
      {
        text: "Critics dismissed her vision as quixotic, too idealistic to ever be realized in the real world.",
        vocabulary: "quixotic",
        definition: "Exceedingly idealistic; unrealistic and impractical, often in a noble or romantic way.",
        question: "Why do the critics describe her vision as 'quixotic'?",
        choices: [
          { text: "They believe her ideals are too unrealistic to ever be achieved.", correct: true },
          { text: "They think her work is simple and easy to build.", correct: false },
          { text: "They believe her work is too practical and boring.", correct: false },
          { text: "They think she copied her designs from someone else.", correct: false },
        ],
      },
      {
        text: "Yet she remained undeterred, her conviction as immovable as the mountains she once loved.",
        vocabulary: "undeterred",
        definition: "Not discouraged or prevented from continuing despite difficulties or opposition.",
        question: "What does her being 'undeterred' reveal about her character?",
        choices: [
          { text: "She is resilient and refuses to give up on her vision despite criticism.", correct: true },
          { text: "She easily gives up when people criticize her.", correct: false },
          { text: "She is indifferent and does not care about her work.", correct: false },
          { text: "She is confused about what she truly wants to do.", correct: false },
        ],
      },
      {
        text: "There was a serene audacity in her sketches — a boldness that defied all conventional rules.",
        vocabulary: "audacity",
        definition: "A willingness to take bold risks; daring and fearless behavior.",
        question: "What does the term 'audacity' suggest about her sketches?",
        choices: [
          { text: "They boldly break conventions and push boundaries.", correct: true },
          { text: "They timidly follow all traditional rules.", correct: false },
          { text: "They are dull and unremarkable.", correct: false },
          { text: "They are incomplete and sloppy.", correct: false },
        ],
      },
      {
        text: "Her colleagues called her enigmatic, a woman whose silence spoke louder than their words.",
        vocabulary: "enigmatic",
        definition: "Difficult to interpret or understand; mysterious and puzzling.",
        question: "Why is she described as 'enigmatic'?",
        choices: [
          { text: "She has a mysterious quality that others find difficult to fully understand.", correct: true },
          { text: "She talks constantly and reveals everything about herself.", correct: false },
          { text: "She is easily understood by everyone around her.", correct: false },
          { text: "She has no personality at all.", correct: false },
        ],
      },
      {
        text: "She often wandered through forgotten ruins, finding inspiration in their decaying grandeur.",
        vocabulary: "grandeur",
        definition: "Splendor and impressiveness, especially of appearance or style; magnificence.",
        question: "What does she find in the 'decaying grandeur' of ruins?",
        choices: [
          { text: "She sees beauty and inspiration in the remains of past greatness.", correct: true },
          { text: "She only sees rubble and trash with no value.", correct: false },
          { text: "She wants to destroy the ruins completely.", correct: false },
          { text: "She ignores ruins and only cares about modern buildings.", correct: false },
        ],
      },
      {
        text: "For her, architecture was not a profession but a profound meditation on human impermanence.",
        vocabulary: "impermanence",
        definition: "The state or fact of lasting for only a period of time; the quality of being temporary.",
        question: "Why does she view architecture as a 'meditation on human impermanence'?",
        choices: [
          { text: "She sees buildings as temporary reflections of humanity's fleeting existence.", correct: true },
          { text: "She believes buildings are eternal and never decay.", correct: false },
          { text: "She thinks architecture has nothing to do with human life.", correct: false },
          { text: "She only cares about how much money she can make.", correct: false },
        ],
      },
      {
        text: "Her blueprints were meticulous, every line deliberate and every curve a philosophical statement.",
        vocabulary: "meticulous",
        definition: "Showing great attention to detail; very careful and precise.",
        question: "What does 'meticulous blueprints' reveal about her working style?",
        choices: [
          { text: "She works with extreme care and attention to every detail.", correct: true },
          { text: "She works carelessly without any planning.", correct: false },
          { text: "She copies the work of other architects.", correct: false },
          { text: "She does not care about precision at all.", correct: false },
        ],
      },
      {
        text: "She once said that all cities are fleeting poems written in stone and glass.",
        vocabulary: "fleeting",
        definition: "Lasting for a very short time; passing quickly.",
        question: "What does calling cities 'fleeting poems' suggest about her philosophy?",
        choices: [
          { text: "She sees cities as temporary but beautiful expressions of human creativity.", correct: true },
          { text: "She believes cities are permanent and never change.", correct: false },
          { text: "She thinks cities have no artistic value whatsoever.", correct: false },
          { text: "She wants to destroy all existing cities.", correct: false },
        ],
      },
      {
        text: "Her vision was often misunderstood, yet she refused to compromise her principles.",
        vocabulary: "compromise",
        definition: "To settle a dispute by making concessions; to weaken or give up one's standards.",
        question: "What does her refusal to 'compromise' reveal about her?",
        choices: [
          { text: "She remains true to her ideals even when misunderstood by others.", correct: true },
          { text: "She easily changes her beliefs to please others.", correct: false },
          { text: "She has no strong beliefs of her own.", correct: false },
          { text: "She only cares about what others think of her.", correct: false },
        ],
      },
      {
        text: "In the end, her creations stood as silent testaments to a vision that transcended time.",
        vocabulary: "testament",
        definition: "Something that serves as a formal or solemn evidence or proof of a fact or belief.",
        question: "Why are her creations called 'silent testaments'?",
        choices: [
          { text: "They stand as lasting proof of her timeless vision and ideals.", correct: true },
          { text: "They are literally made of silence and sound waves.", correct: false },
          { text: "They crumble and disappear immediately.", correct: false },
          { text: "They have no meaning and are quickly forgotten.", correct: false },
        ],
      },
      {
        text: "Even in her old age, she never ceased dreaming of cities yet to be built.",
        vocabulary: "cease",
        definition: "To bring or come to an end; to stop happening or existing.",
        question: "What does her refusal to 'cease dreaming' reveal about her spirit?",
        choices: [
          { text: "Her creative spirit remains alive and hopeful despite her age.", correct: true },
          { text: "She has given up on all her dreams completely.", correct: false },
          { text: "She only thinks about the past and not the future.", correct: false },
          { text: "She no longer cares about architecture at all.", correct: false },
        ],
      },
      {
        text: "A young apprentice once asked her the secret to true greatness, and she simply smiled.",
        vocabulary: "apprentice",
        definition: "A person who is learning a trade or art from a skilled employer.",
        question: "Why did she smile instead of answering the apprentice's question?",
        choices: [
          { text: "The answer was something that could only be learned through experience, not words.", correct: true },
          { text: "She did not understand the question at all.", correct: false },
          { text: "She was angry at the apprentice for asking.", correct: false },
          { text: "She had forgotten what greatness meant.", correct: false },
        ],
      },
      {
        text: "Her silence, in that moment, was more instructive than any lecture could ever be.",
        vocabulary: "instructive",
        definition: "Serving to teach or provide useful information; educational and enlightening.",
        question: "What does her silence being 'instructive' reveal?",
        choices: [
          { text: "Her example and presence alone taught the apprentice more than words could.", correct: true },
          { text: "She refused to teach the apprentice anything.", correct: false },
          { text: "She did not know how to explain anything.", correct: false },
          { text: "The apprentice learned nothing from her.", correct: false },
        ],
      },
      {
        text: "When she finally passed, her final wish was for her sketches to be shared with the world.",
        vocabulary: "passed",
        definition: "A euphemism for dying; to have left this life.",
        question: "What does her final wish reveal about her values?",
        choices: [
          { text: "She valued sharing her vision over keeping it private or profitable.", correct: true },
          { text: "She wanted to destroy all her work before dying.", correct: false },
          { text: "She only cared about her personal wealth.", correct: false },
          { text: "She never wanted anyone to see her designs.", correct: false },
        ],
      },
      {
        text: "And so, the architect of dreams left behind not buildings, but a way of seeing the world.",
        vocabulary: "architect",
        definition: "A person who designs buildings and oversees their construction; one who creates a plan or framework.",
        question: "Why is she called an 'architect of dreams' rather than just an architect?",
        choices: [
          { text: "She built not just structures, but also ideas and ways of perceiving reality.", correct: true },
          { text: "She only designed ordinary buildings with no special meaning.", correct: false },
          { text: "She refused to design anything at all during her life.", correct: false },
          { text: "She worked only as a construction worker, not a designer.", correct: false },
        ],
      },
    ],
  },
};